# Generated by Django 4.2 on 2026-04-30 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name="Ім'я")),
                ('email', models.EmailField(max_length=254, verbose_name='Електронна пошта')),
                ('phone', models.CharField(max_length=16, verbose_name='Номер телефону')),
                ('message', models.TextField(verbose_name='Текст повідомлення')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата та час звернення')),
            ],
            options={
                'verbose_name': 'Контактна форма',
                'verbose_name_plural': 'Контактні форми',
            },
        ),
    ]
