# Generated by Django 4.2 on 2026-04-30 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contactmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date and time of question'),
        ),
    ]
