# Generated by Django 4.2.30 on 2026-05-22 23:58

from django.db import migrations, models
 

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_homepage_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Title/name of the company')),
                ('subtitle', models.CharField(max_length=128, verbose_name='Subtitle of the company')),
                ('logo', models.ImageField(upload_to='header_logo/', verbose_name='Logo of the company')),
                ('phone', models.CharField(max_length=16, verbose_name='Phone number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Header settings',
            },
        ),
        # migrations.RunPython(create_default_header),
    ]
