# Generated by Django 6.0.4 on 2026-05-30 21:56

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_homepage_delete_test'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=128, verbose_name='Footer caption')),
                ('rights', models.CharField(max_length=128, verbose_name='Rights')),
            ],
            options={
                'verbose_name': 'Footer settings',
            },
        ),
        migrations.CreateModel(
            name='HeaderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Header settings',
            },
        ),
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('image', 0)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {})}),
        ),
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Title/name of the company')),
                ('subtitle', models.CharField(max_length=128, verbose_name='Subtitle of the company')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook URL')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram URL')),
                ('favicon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Website favicon')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Website logo')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Company information',
            },
        ),
        migrations.CreateModel(
            name='ContentPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('preview_title', models.CharField(max_length=256, verbose_name='Preview card title')),
                ('preview_description', models.CharField(max_length=512, verbose_name='Preview card description')),
                ('body', wagtail.fields.StreamField([('image', 0), ('rtfbody', 1), ('images2p1', 4), ('images3p2', 6), ('gallery', 8), ('imagestext', 11)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 3: ('wagtail.blocks.ListBlock', (2,), {'label': 'Add images', 'max_num': 3, 'min_num': 3}), 4: ('wagtail.blocks.StructBlock', [[('images', 3)]], {}), 5: ('wagtail.blocks.ListBlock', (2,), {'label': 'Add images', 'max_num': 5, 'min_num': 5}), 6: ('wagtail.blocks.StructBlock', [[('images', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (2,), {'label': 'Add images', 'min_num': 1}), 8: ('wagtail.blocks.StructBlock', [[('images', 7)]], {}), 9: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('img-left', 'Images on the left, text on the right'), ('img-right', 'Text on the left, images on the right')], 'label': 'Elements layout'}), 10: ('wagtail.blocks.RichTextBlock', (), {'label': 'Text'}), 11: ('wagtail.blocks.StructBlock', [[('layout', 9), ('images', 7), ('text', 10)]], {})})),
                ('preview_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Preview card image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
