# Generated by Django 4.2.30 on 2026-05-23 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_headersettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=16, verbose_name='Phone number')),
                ('instagram_url', models.CharField(max_length=512, verbose_name='Instagram URL')),
                ('facebook_url', models.CharField(max_length=512, verbose_name='Facebook URL')),
            ],
            options={
                'verbose_name': 'Footer settings',
            },
        ),
        # migrations.RunPython(create_default_footer),
    ]
