# Generated by Django 4.2.30 on 2026-05-23 11:57

from django.db import migrations


def create_default_header_footer(apps, schema_editor):
    HeaderSnippet = apps.get_model('main', 'HeaderSettings')
    FooterSnippet = apps.get_model('main', 'FooterSettings')

    HeaderSnippet.objects.get_or_create(
        title="STAR Creatiff",
        subtitle="realizamos ideas",
        logo="header_logo/default_logo.png",
        phone="951 392 250",
        email="star.creatiff@gmail.com",
    )

    FooterSnippet.objects.get_or_create(
        email="star.creatiff@gmail.com",
        phone="951 392 250",
        instagram_url="https://www.instagram.com/",
        facebook_url="https://www.facebook.com/",
    )


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_footersettings'),
    ]

    operations = [
        migrations.RunPython(create_default_header_footer),
    ]
