# Generated by Django 4.2.30 on 2026-05-31 00:47

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_homepage_body_homepage_hero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='hero',
            field=wagtail.fields.StreamField([('hero', 10)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'First row of the caption', 'max_length': 128}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Second row of the caption', 'max_length': 128}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Big text paragraph', 'max_length': 1024}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Small text paragraph', 'max_length': 1024}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Button text', 'max_length': 64}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Statistics number', 'max_length': 8}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Statistics text', 'max_length': 64}), 7: ('wagtail.blocks.StructBlock', [[('stats_number', 5), ('stats_text', 6)]], {}), 8: ('wagtail.blocks.ListBlock', (7,), {'label': 'Statistics'}), 9: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Main hero image', 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('caption_first_row', 0), ('caption_second_row', 1), ('big_paragraph', 2), ('small_paragraph', 3), ('button', 4), ('statistics', 8), ('image', 9)]], {})}),
        ),
    ]
