# Generated by Django 6.0.4 on 2026-05-25 10:43

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_create_header_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='rtfbody',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='Body'),
        ),
    ]
