# Generated by Django 4.2.30 on 2026-05-31 11:06

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_homepage_hero'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='partners',
            field=wagtail.fields.StreamField([('partners', 4)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Partners logo', 'required': True}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Partners name', 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('partner_logo', 0), ('partner_name', 1)]], {'required': False}), 3: ('wagtail.blocks.ListBlock', (2,), {'label': 'Add partner'}), 4: ('wagtail.blocks.StructBlock', [[('partners', 3)]], {})}),
        ),
    ]
