# Generated by Django 4.2.30 on 2026-05-31 13:28

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_homepage_partners'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='banner',
            field=wagtail.fields.StreamField([('banner', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Banner title', 'max_length': 256}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Banner button text', 'max_length': 128}), 2: ('wagtail.blocks.StructBlock', [[('heading', 0), ('button', 1)]], {})}),
        ),
        migrations.AddField(
            model_name='homepage',
            name='detailes_button',
            field=models.CharField(default=str, max_length=64, verbose_name='Details button'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='promo',
            field=wagtail.fields.StreamField([('promo', 9)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Heading of a section', 'max_length': 250}), 1: ('wagtail.blocks.TextBlock', (), {'label': 'Main description'}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Title of point', 'max_length': 128}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Text of point', 'max_length': 256}), 4: ('wagtail.blocks.StructBlock', [[('title', 2), ('text', 3)]], {}), 5: ('wagtail.blocks.ListBlock', (4,), {'label': 'List of benefits'}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Text before button', 'max_length': 250, 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'default': 'Связаться с нами', 'label': 'Button text', 'max_length': 50}), 8: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Image'}), 9: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('benefits', 5), ('cta_text', 6), ('button_text', 7), ('image', 8)]], {})}),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='partners',
            field=wagtail.fields.StreamField([('partners', 4)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Partners logo', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Partners name', 'max_length': 256}), 2: ('wagtail.blocks.StructBlock', [[('partner_logo', 0), ('partner_name', 1)]], {'required': False}), 3: ('wagtail.blocks.ListBlock', (2,), {'label': 'Add partner'}), 4: ('wagtail.blocks.StructBlock', [[('partners', 3)]], {})}),
        ),
    ]
