# Generated by Django 4.2.30 on 2026-05-31 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_homepage_banner_homepage_detailes_button_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='detailes_button',
            new_name='details_button',
        ),
    ]
