# Generated by Django 4.2.30 on 2026-06-01 18:53

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_detailes_button_homepage_details_button'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='promo',
            field=wagtail.fields.StreamField([('promo', 9)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Heading of a section', 'max_length': 250}), 1: ('wagtail.blocks.TextBlock', (), {'label': 'Main description'}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Title of point', 'max_length': 128}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Text of point', 'max_length': 256}), 4: ('wagtail.blocks.StructBlock', [[('title', 2), ('text', 3)]], {}), 5: ('wagtail.blocks.ListBlock', (4,), {'label': 'List of benefits'}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Text before button', 'max_length': 250, 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'default': 'Contact with us', 'label': 'Button text', 'max_length': 50}), 8: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Image'}), 9: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('benefits', 5), ('cta_text', 6), ('button_text', 7), ('image', 8)]], {})}),
        ),
    ]
