# Generated by Django 6.0.4 on 2026-06-02 23:31

import django.db.models.deletion
import uuid
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_detailes_button_homepage_details_button'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpage',
            name='body',
            field=wagtail.fields.StreamField([('image', 0), ('rtfbody', 1), ('images2p1', 4), ('images3p2', 6), ('gallery', 8), ('imagestext', 11)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {'label': 'Text editor'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 3: ('wagtail.blocks.ListBlock', (2,), {'label': 'Add images', 'max_num': 3, 'min_num': 3}), 4: ('wagtail.blocks.StructBlock', [[('images', 3)]], {}), 5: ('wagtail.blocks.ListBlock', (2,), {'label': 'Add images', 'max_num': 5, 'min_num': 5}), 6: ('wagtail.blocks.StructBlock', [[('images', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (2,), {'label': 'Add images', 'min_num': 1}), 8: ('wagtail.blocks.StructBlock', [[('images', 7)]], {}), 9: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('img-left', 'Images on the left, text on the right'), ('img-right', 'Text on the left, images on the right')], 'label': 'Elements layout'}), 10: ('wagtail.blocks.RichTextBlock', (), {'label': 'Text'}), 11: ('wagtail.blocks.StructBlock', [[('layout', 9), ('images', 7), ('text', 10)]], {})}),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='promo',
            field=wagtail.fields.StreamField([('promo', 9)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Heading of a section', 'max_length': 250}), 1: ('wagtail.blocks.TextBlock', (), {'label': 'Main description'}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Title of point', 'max_length': 128}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Text of point', 'max_length': 256}), 4: ('wagtail.blocks.StructBlock', [[('title', 2), ('text', 3)]], {}), 5: ('wagtail.blocks.ListBlock', (4,), {'label': 'List of benefits'}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Text before button', 'max_length': 250, 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'default': 'Contact with us', 'label': 'Button text', 'max_length': 50}), 8: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Image'}), 9: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('benefits', 5), ('cta_text', 6), ('button_text', 7), ('image', 8)]], {})}),
        ),
        migrations.CreateModel(
            name='ContactFormSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('title', models.CharField(blank=True, max_length=128, verbose_name='Form title')),
                ('recipient_email', models.EmailField(blank=True, max_length=254, verbose_name='Email for receiving forms')),
                ('phone_required', models.BooleanField(default=False, verbose_name='Is phone required')),
                ('name_label', models.CharField(blank=True, max_length=64, verbose_name="Label for field 'Name'")),
                ('name_placeholder', models.CharField(blank=True, max_length=128, verbose_name="Placeholder for field 'Name'")),
                ('email_label', models.CharField(blank=True, max_length=64, verbose_name="Label for field 'Email'")),
                ('email_placeholder', models.CharField(blank=True, max_length=128, verbose_name="Placeholder for field 'Email'")),
                ('phone_label', models.CharField(blank=True, max_length=64, verbose_name="Label for field 'Phone'")),
                ('phone_placeholder', models.CharField(blank=True, max_length=128, verbose_name="Placeholder for field 'Phone'")),
                ('message_label', models.CharField(blank=True, max_length=64, verbose_name="Label for field 'message'")),
                ('message_placeholder', models.CharField(blank=True, max_length=256, verbose_name="Placeholder for field 'Message'")),
                ('submit_button_text', models.CharField(blank=True, max_length=64, verbose_name='Confirmation button text')),
                ('success_message', models.CharField(blank=True, max_length=256, verbose_name='Message for сonfirmation that the form was successfully submitted')),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale', verbose_name='locale')),
            ],
            options={
                'verbose_name': 'Contact form settings',
                'constraints': [models.UniqueConstraint(fields=('translation_key', 'locale'), name='unique_translation_key_locale_main_contactformsettings')],
            },
        ),
    ]
