# Generated by Django 4.2.30 on 2026-06-05 13:50

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_homepage_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='load_more_button',
            field=models.CharField(default='Load More', max_length=64, verbose_name='Button for loading more tiles (only on phones)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='partners',
            field=wagtail.fields.StreamField([('partners', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Partners section title', 'max_length': 256}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Partners logo', 'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Partners name', 'max_length': 256}), 3: ('wagtail.blocks.StructBlock', [[('partner_logo', 1), ('partner_name', 2)]], {'required': False}), 4: ('wagtail.blocks.ListBlock', (3,), {'label': 'Add partner'}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('partners', 4)]], {})}),
        ),
    ]
