# Generated by Django 6.0.4 on 2026-06-02 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_homepage_promo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFormSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128, verbose_name='Form title')),
                ('recipient_email', models.EmailField(blank=True, max_length=254, verbose_name='Email for receiving forms')),
                ('phone_required', models.BooleanField(default=False, verbose_name='Is phone required')),
                ('name_label', models.CharField(blank=True, max_length=64, verbose_name="Label for field 'Name'")),
                ('name_placeholder', models.CharField(blank=True, max_length=128, verbose_name="Placeholder for field 'Name'")),
                ('email_label', models.CharField(blank=True, max_length=64, verbose_name="Label for field 'Email'")),
                ('email_placeholder', models.CharField(blank=True, max_length=128, verbose_name="Placeholder for field 'Email'")),
                ('phone_label', models.CharField(blank=True, max_length=64, verbose_name="Label for field 'Phone'")),
                ('phone_placeholder', models.CharField(blank=True, max_length=128, verbose_name="Placeholder for field 'Phone'")),
                ('message_label', models.CharField(blank=True, max_length=64, verbose_name="Label for field 'message'")),
                ('message_placeholder', models.CharField(blank=True, max_length=256, verbose_name="Placeholder for field 'Message'")),
                ('submit_button_text', models.CharField(blank=True, max_length=64, verbose_name='Confirmation button text')),
                ('success_message', models.CharField(blank=True, max_length=256, verbose_name='Message for сonfirmation that the form was successfully submitted')),
            ],
            options={
                'verbose_name': 'Contact form settings',
            },
        ),
    ]
