# Generated by Django 4.2.30 on 2026-06-03 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_contentpage_body_alter_homepage_promo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='details_button',
            field=models.CharField(default='Details', max_length=64, verbose_name='Details button'),
        ),
    ]
