# Generated by Django 6.0.4 on 2026-06-08 21:16

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_homepage_load_more_button_alter_homepage_partners'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactformsettings',
            name='recipient_email',
        ),
        migrations.AddField(
            model_name='companysettings',
            name='recipient_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email for receiving forms'),
        ),
        migrations.AlterField(
            model_name='contentpage',
            name='body',
            field=wagtail.fields.StreamField([('image', 0), ('rtfbody', 1), ('images2p1', 4), ('images3p2', 6), ('images3oversized', 4), ('images2', 8), ('gallery', 11), ('imagestext', 14)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {'label': 'Text editor'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 3: ('wagtail.blocks.ListBlock', (2,), {'label': 'Add images', 'max_num': 3, 'min_num': 3}), 4: ('wagtail.blocks.StructBlock', [[('images', 3)]], {}), 5: ('wagtail.blocks.ListBlock', (2,), {'label': 'Add images', 'max_num': 5, 'min_num': 5}), 6: ('wagtail.blocks.StructBlock', [[('images', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (2,), {'label': 'Add images', 'max_num': 2, 'min_num': 2}), 8: ('wagtail.blocks.StructBlock', [[('images', 7)]], {}), 9: ('wagtail.blocks.CharBlock', (), {'blank': True, 'label': 'Heading of a gallery', 'max_length': 250, 'null': True}), 10: ('wagtail.blocks.ListBlock', (2,), {'label': 'Add images', 'min_num': 1}), 11: ('wagtail.blocks.StructBlock', [[('title', 9), ('images', 10)]], {}), 12: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('img-left', 'Images on the left, text on the right'), ('img-right', 'Text on the left, images on the right')], 'label': 'Elements layout'}), 13: ('wagtail.blocks.RichTextBlock', (), {'label': 'Text'}), 14: ('wagtail.blocks.StructBlock', [[('layout', 12), ('images', 10), ('text', 13)]], {})}),
        ),
    ]
