# Generated by Django 6.0.4 on 2026-06-02 11:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_contactformsettings_homepage_contact_form_settings'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactformsettings',
            name='locale',
            field=models.ForeignKey(default=str, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale', verbose_name='locale'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactformsettings',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddConstraint(
            model_name='contactformsettings',
            constraint=models.UniqueConstraint(fields=('translation_key', 'locale'), name='unique_translation_key_locale_main_contactformsettings'),
        ),
    ]
