# Generated by Django 6.0.4 on 2026-06-08 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_contactformsettings_recipient_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactformsettings',
            name='error_message',
            field=models.CharField(blank=True, max_length=256, verbose_name='Message for notification that some error has been occured'),
        ),
    ]
