# Generated by Django 4.2.30 on 2026-06-11 22:29

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_contactformsettings_error_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpage',
            name='body',
            field=wagtail.fields.StreamField([('image', 0), ('rtfbody', 1), ('images2p1', 4), ('images3p2', 6), ('images3oversized', 4), ('images3p3', 8), ('images2', 10), ('images4', 12), ('gallery', 15), ('imagestext', 18)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {'label': 'Text editor'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 3: ('wagtail.blocks.ListBlock', (2,), {'label': 'Add images', 'max_num': 3, 'min_num': 3}), 4: ('wagtail.blocks.StructBlock', [[('images', 3)]], {}), 5: ('wagtail.blocks.ListBlock', (2,), {'label': 'Add images', 'max_num': 5, 'min_num': 5}), 6: ('wagtail.blocks.StructBlock', [[('images', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (2,), {'label': 'Add images', 'max_num': 6, 'min_num': 6}), 8: ('wagtail.blocks.StructBlock', [[('images', 7)]], {}), 9: ('wagtail.blocks.ListBlock', (2,), {'label': 'Add images', 'max_num': 2, 'min_num': 2}), 10: ('wagtail.blocks.StructBlock', [[('images', 9)]], {}), 11: ('wagtail.blocks.ListBlock', (2,), {'label': 'Add images', 'max_num': 4, 'min_num': 4}), 12: ('wagtail.blocks.StructBlock', [[('images', 11)]], {}), 13: ('wagtail.blocks.CharBlock', (), {'blank': True, 'label': 'Heading of a gallery', 'max_length': 250, 'null': True}), 14: ('wagtail.blocks.ListBlock', (2,), {'label': 'Add images', 'min_num': 1}), 15: ('wagtail.blocks.StructBlock', [[('title', 13), ('images', 14)]], {}), 16: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('img-left', 'Images on the left, text on the right'), ('img-right', 'Text on the left, images on the right')], 'label': 'Elements layout'}), 17: ('wagtail.blocks.RichTextBlock', (), {'label': 'Text'}), 18: ('wagtail.blocks.StructBlock', [[('layout', 16), ('images', 14), ('text', 17)]], {})}),
        ),
    ]
